name: Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      id-token: write

    steps:
      - name: Checkout picotls
        uses: actions/checkout@v3
        with:
          repository: 'h2o/picotls'
          path: 'picotls'
          submodules: 'true'

      - name: Setup picotls
        run: |
          cd $GITHUB_WORKSPACE/picotls && cmake -DCMAKE_C_FLAGS="-std=c99 -Wall -O2 -g -fPIC" .
          make -j`nproc --all`

      - name: Checkout picoquic
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.ACTION_TOKEN }}
          repository: 'clarkzjw/picoquic'
          path: 'picoquic'

      - name: Setup dependencies
        run: |
          sudo apt-get update && sudo apt-get install -y git build-essential cmake libeigen3-dev libcurl4-openssl-dev libxml2-dev
          cd $GITHUB_WORKSPACE/picoquic && cmake -DCMAKE_C_FLAGS="-std=c99 -Wall -O2 -g -fPIC" .
          make -j`nproc --all`
          sudo make install

#      - name: Checkout Chrono
#        uses: actions/checkout@v3
#        with:
#          repository: 'projectchrono/chrono'
#          path: 'chrono'
#
#      - name: Setup Chrono
#        run: |
#          cd $GITHUB_WORKSPACE/chrono
#          mkdir cmakebuild
#          cd cmakebuild
#          cmake -DENABLE_MODULE_POSTPROCESS=on ..
#          make -j`nproc --all`
#          sudo make install

      - name: Checkout player
        uses: actions/checkout@v3
        with:
          path: 'player'

      - name: Build
        run: |
          cd $GITHUB_WORKSPACE/player
          cmake .
          make -j`nproc --all`

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v3.1.0
        with:
          name: build
          path: |
            player/tplayer
            player/tserver
          if-no-files-found: error
